# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '11.0'

target 'C:\Users\1418\CordovaSms\platforms\ios\HelloCordova' do
	project 'C:\Users\1418\CordovaSms\platforms\ios\HelloCordova.xcodeproj'

end
